### ISSUE TITLE
Start using one of the go web framework/libs to handle the routing and context

### ISSUE THREAD

**Issue by rach** [rach/pome#1]
I did the first version using the built-in http package as I had never used go before.
It's quite limited and it will help to have gzip and others.

So far, I liked http://www.gorillatoolkit.org/ as it's more of library than a framework. Any suggestion are welcomed.

**Comment by ctrlrsf** [comment]
Using built in http package is working so far. No sure using a framework would provide much of a benefit at this point.

**Comment by rlayte** [comment]
I'm not sure it's worth adding a dependency either tbh. The app is mainly just serving static files and a couple of api requests so it seems like overkill to me. However, if the api requests become more complicated (more metrics, filtering, etc) then you could look at [httprouter](https://github.com/julienschmidt/httprouter). It doesn't add much to the standard web server, but gives you an easier way to set up routes, without adding a lot of bloat.

**Comment by rach** [comment]
Good to know. Thanks for your input. 
I will close this issue for now. Maybe we can reopen in the future if we have the need.
