### ISSUE TITLE
Scan error

### ISSUE THREAD

**Issue by kkoch986** [rach/pome#23]
Tried starting it up and got the following error: 

```
2016/01/05 10:33:02 Starting Pome 0.1.0
2016/01/05 10:33:02 Application will be available at http://127.0.0.1:2345
2016/01/05 10:33:02 sql: Scan error on column index 3: converting string "6.55917056e+08" to a int: strconv.ParseInt: parsing "6.55917056e+08": invalid syntax
```

Could it be because of our use of bigints?

**Comment by amolk** [comment]
+1

**Comment by rach** [comment]
I think that's a duplicate of #22 I will have look at it

**Comment by kkoch986** [comment]
sorry about that we must have both opened them around the same time

**Comment by rach** [comment]
Thanks for reporting it. I think that I may have a fix for this bug. See #22 and https://github.com/rach/pome/commit/b051abf4f978ed48baa94ca3e5aeca9fd4388dcb
I'm closing this ticket as it's a dublicate. If this fix solve your problem then I will release 0.1.2

**Comment by amolk** [comment]
Thank you Rach! Looking forward to trying out pome.

Best,
Amol

**Comment by rach** [comment]
Thanks @amolk . My attempt to fix it was wrong, I found the query which create the error so I should be able to provide a fix a bit later on.

**Comment by kkoch986** [comment]
great thanks!
